---
apiVersion: v1
kind: Service
metadata:
  name: test-affinity
  labels:
    app.kubernetes.io/name: test-affinity
    app.kubernetes.io/instance: test-affinity
spec:
  selector:
    app.kubernetes.io/name: test-affinity
    app.kubernetes.io/instance: test-affinity
  ports:
    -
      port: 80
      targetPort: 80
      protocol: TCP
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-affinity
  labels:
    app.kubernetes.io/name: test-affinity
    app.kubernetes.io/instance: test-affinity
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-affinity
      app.kubernetes.io/instance: test-affinity
  replicas: 3
  template:
    metadata:
      name: test-affinity
      labels:
        app.kubernetes.io/name: test-affinity
        app.kubernetes.io/instance: test-affinity
    spec:
      # tolerations:
      #   -
      #     key: node-role.kubernetes.io/control-plane
      #     operator: Exists
      #     effect: NoSchedule
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            -
              labelSelector:
                matchExpressions:
                  -
                    key: app.kubernetes.io/name
                    operator: In
                    values:
                      - test-affinity
                  -
                    key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - test-affinity
              topologyKey: kubernetes.io/hostname
      containers:
        -
          name: whoami
          image: docker.io/traefik/whoami:latest
          imagePullPolicy: Never
          ports:
            -
              name: http
              containerPort: 80
              protocol: TCP
